config-version: 1

# The max team size for teams. If a team is larger than a dungeon allows, then the player will select who to bring.
max-players-per-team: 10

# The priority of each room. Every room is provided here as an additional aid for every room name.
# The starting room will always try to be connected to the main structure with a path towards the boss.
starting-room-priority:
  - MUSIC
  - BANQUET
  - BEDROOM
  - LIBRARY
  - CORRIDOR
  - STAIRWAY
  - CROSS
  - CRYPT
  - RESERVOIR
  - CISTERN
  - OSSUARY
  - KITCHEN
  - CREEPER
  - ENDER
  - ABYSS
  - PRISON
  - MUSIC
  - BREWING
  - PANOPTICON
  - SCULK
  - BTEAM
  - SMITH
  - PIT
  - BALCONY
  - IMPERIAL_STAIRWAY
  - ENTRANCE

# If set to true, players will spectate their dungeon after dying. Otherw
spectator-mode:
  enabled: true
  # If true, then the spectator will be locked to teammembers only.
  only-on-team: true


invitation-gui:
  structure:
    - "# # # # # # # # #"
    - "# # Y # # # N # #"
    - "# # # # I # # # #"
  ingredients:
    '#':
      type: minecraft:black_stained_glass_pane
      hideTooltip: true
    'Y':
      type: minecraft:lime_stained_glass_pane
      display-name: "<green>Confirm"
    'N':
      type: minecraft:lime_stained_glass_pane
      display-name: "<red>Deny"
    'I':
      type: minecraft:paper
      display-name: "<yellow>Information"
      lore:
        - " "
        - "<gold>Dungeon Type: {type}"
        - "<white>You've been invited by {player} to a Dungeon!"